### ISSUE TITLE
Closing dialogs with dynamic components

### ISSUE THREAD

**Issue by Disane87** [sweetalert2/ngx-sweetalert2#100]
First of all, thank you for your awesome work!
We've implemented a way to integrate other components within sweetalert, because we need to open dialogs with our components over the code.

You can see this in the following stackblitz:
https://stackblitz.com/edit/dsn-sweetalert-dynamic-comp

It works pretty well, only on the native `close()` of sweetalert, it breaks all further dialogs and dynamic component instantiation.
As I investigated, sweetalert is not resolving or rejecting the promise for the close, so the promise stays open and behaves like this. But I don't know how to change this.

For us, the integration of dynamic components and closing them programatically is a must, so it would be really great, if we can investigate this and fix it :)

The stackblitz above, is a full functional example and reproduction of the issue.

Steps to reproduce:
- Open a dialog and close it with the sweetalert buttons is ok:
![image](https://user-images.githubusercontent.com/956158/50588599-270a4580-0e83-11e9-984d-bfe9476a8f7a.png)

- Opening it again and press button "break it":
![image](https://user-images.githubusercontent.com/956158/50588644-4acd8b80-0e83-11e9-8447-8b018f15e6a6.png)

- Dialog closes (as whished)
- Opening the dialog again shows no dynamic component:
![image](https://user-images.githubusercontent.com/956158/50588679-6e90d180-0e83-11e9-8adf-f21bda2691ef.png)

We have wrapped your component into an own dialog-component `dialog.component.ts`. Here is the dynamic instantiation of components to.

In the Template we have a seperate way for a placeholder, where the component is puttin in ( we access this within `dialog.component.ts` via 

```ts
 @ViewChild('placeHolder', { read: ViewContainerRef }) private _placeHolder: ViewContainerRef;
```

The method `showDialog` checks if there is a component (and parameters) in place and starts the process for attaching the component to the template:

```ts
public showDialog(): Promise<any> {
    let comp: Type<any>;
    debugger;
    if (this.options.component) {
      comp = this.options.component;
      delete this.options.component;
    }

    this.dialog.options = this.options;
    const dialogPromise = this.dialog.show();

    this.dialog.open.pipe(first()).subscribe(x => {
      if (comp) {
        this.compRef = this.createComponent(this._placeHolder, comp, this.options.componentParams);
      }
    });

    return dialogPromise;
  }
```

Via `dialog.service.ts` we show our dialog and fill the `dialog.component` with options to show it, like in `app.component.ts`:
```ts
showDialogWithClose() {
    const componentParams: any[] = [];
    componentParams['withCloseButton'] = true;

    let dialogOptions: DialogOptions<any> = {
      
      title: "With native close 🤷",
      showConfirmButton: true,
      showCancelButton: true,
      component: TestComponent,
      componentParams: componentParams,
      grow: false,
      width: '25%'
    };
    this.dialogService.showDialog(dialogOptions).then((dismisReason) => this.dismisReason = dismisReason, (err) => this.dismisReason = err);
  }
```

Would be great if you can assist us the fix this strange behavior.

**Comment by Disane87** [comment]
Any updates on this? @toverux do you have a clue how we can fix this?

**Comment by Disane87** [comment]
As I've seen, there is a potential fix for that problem in version 8.0.0 of sweetalert2, see attached issue:
https://github.com/sweetalert2/sweetalert2/pull/1379

Is there any eta for an implementation of this angularf wrapper for version 8.0.0?

**Comment by limonte** [comment]
Good news!

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```

@Disane87 let us know if the new release will solve this issue.

**Comment by Disane87** [comment]
Thank you for this good news @limonte. Meanwhile we had to switch to another package because sweetalert does not support multiple alerts at one. 

We used sweetalert for settings dialogs and when an async background operation failed, we raised an error message with sweetalert, which cutted off the first dialog ungracefully. 

Bit I‘ll gonna try this in other projects :)
