### ISSUE TITLE
Automated releasing doesn't work

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#104]
https://travis-ci.org/sweetalert2/ngx-sweetalert2/builds/482000314

```
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 Not found : @toverux/ngx-sweetalert2
npm ERR! 404 
npm ERR! 404  '@toverux/ngx-sweetalert2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by limonte** [comment]
dear npm, how the fuck `@toverux/ngx-sweetalert2` is not in the registry? https://www.npmjs.com/package/@toverux/ngx-sweetalert2

**Comment by limonte** [comment]
My gut feeling tells me that this issue is somehow related to https://github.com/sweetalert2/ngx-sweetalert2/issues/85

**Comment by limonte** [comment]
Something is fucked up on the npm side and most probably won't be fixed. 

@toverux is this the right moment to rename the package to `@sweetalert2/ngx-sweetalert2` which will have at least two breaking changes:

- the package name
- swal2 v8 peerDependency

**Comment by toverux** [comment]
Argh, this is annoying.
I'd like to avoid that so lately, but if that's necessary, go for it.

Yes, I delayed my work on the next version a bit to wait for v.8. I documented myself about the new ways to create an Angular library, too.
So I'll probably rewrite the library from scratch and bring support for v8 in the same time.

**Comment by limonte** [comment]
You're going true Google way - rewriting everything from scratch every two-three years :D
