### ISSUE TITLE
incompatible peer dependency

### ISSUE THREAD

**Issue by NTXAggie** [sweetalert2/ngx-sweetalert2#105]
Package "@toverux/ngx-sweetalert2" has an incompatible peer dependency to "sweetalert2" (requires "^7.15.1", would install "8.0.1").

**Comment by limonte** [comment]
The new major release of sweetalert2 has been made recently: https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0

we also updated the installation guide for this package:

```sh
npm install --save sweetalert2@^7.15.1 @toverux/ngx-sweetalert2
```

For existed projects make sure you have something like this in `package.json`:

```js
  "sweetalert2": "^7.x.x"
```

**Comment by limonte** [comment]
Good news!

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```

**Comment by NTXAggie** [comment]
I've updated / tested and it looks to be working well with the latest Angular: `"@angular/core": "^7.2.10"`
