### ISSUE TITLE
Support for version 8

### ISSUE THREAD

**Issue by Franki1986** [sweetalert2/ngx-sweetalert2#107]
Hello,

is there a support for sweetalert2 version 8?

**Comment by toverux** [comment]
Not yet, but this will come soon, as well as (official) Angular 7 support. I'll post in that issue when it arrives.

**Comment by YZahringer** [comment]
Any news?

**Comment by limonte** [comment]
Good day fellas and sorry for the delay in delivering the news.

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```
