### ISSUE TITLE
SwalComponent - ValidationMessage

### ISSUE THREAD

**Issue by vagners2** [sweetalert2/ngx-sweetalert2#109]
Hi,
SwalComponent property does not expose properties validationMessage?
How do i implement validation message for type email?

**Comment by toverux** [comment]
Hi, probably that property has been added to SweetAlert after the latest release of this integration.
A new version supporting SweetAlert 8.x and all the new properties is coming, but in the meantime you can still workaround that by getting a reference to you `<swal>` component and set `mySwal.nativeSwal.validationMessage` before showing the alert.

```html
<swal #mySwal></swal>
```

```ts
class MyComponent {
  @ViewChild('mySwal') private mySwal: SwalComponent;

  public someHandler(): void {
    this.mySwal.nativeSwal.validationMessage = '...';
    this.mySwal.show();
  }
}
```

Stay tuned for official support.
