### ISSUE TITLE
how can i trigger ngx-sweetalert2 

### ISSUE THREAD

**Issue by Ludagon** [sweetalert2/ngx-sweetalert2#110]
I would like to call a swal after something is completed and not only by calling it at HTML. In order to be able to call a success or error swal depending on my method result

**Comment by codemonkey00** [comment]
I couldn't find a way to do this in the HTML so we just have a button click event and do it in typescript.  The below example stays on the same page, but we do the same thing when we need to change pages and inside the .then if it's a success it routes to the next page.

`
        let self = this;  //this is required so swal has access to this
		
	Swal({
            title: 'PAY $' + self.paymentAmount.toFixed(2),
            text: 'Do you wish to pay this amount with the following payment method: **** ' + lastFour + '?',
            type: 'question',
            confirmButtonText: 'Pay',
            showCancelButton: true,
            allowOutsideClick: false,
            showLoaderOnConfirm: true,
            preConfirm: function (value) {
                return new Promise((function (resolve) {
                    (self._PaymentService.payWithNewCard(self.userId, self.paymentAmount, self.newCard)
                        .subscribe((result: PaymentResult) => {
                            resolve(result);
                        })
                    )
                }));
            }
        }).then(function (result) {
            if (result.value != null && result.value.Success == true) {
                Swal('Payment Made!', 'Your payment was processed with receipt number: ' + result.value.Message + '.', 'success');
                //reset the card info fields
                self.resetCardForm();	//updates the card form fields
                self.paymentSuccess();  //updates the payment amount
            }
            else {
                Swal('Payment Failed', result.value.Message, 'error');
                self.cardForm.controls.fbSecurityCode.setValue(null);
            }
        }).catch(function (arg) {
            Swal({
                type: 'error',
                title: 'Canceled',
                text: '',
                html: 'This payment was not made'
            })
        });`

**Comment by toverux** [comment]
```html
<swal #doneSwal></swal>
```

```ts
class MyComponent {
  @ViewChild('doneSwal') private deleteSwal: SwalComponent;

  public doSomething() {
    // ...
    this.doneSwal.show();
  }
}
```
