### ISSUE TITLE
swal.update does not exists

### ISSUE THREAD

**Issue by presercomp** [sweetalert2/ngx-sweetalert2#111]
SweetAlert2 documentation show option 'update', for changes in popup, but, in Angular npm package (7.15.1), show error than update function not exists

**Comment by toverux** [comment]
That is right, `update` is a sweetalert2 8.x feature.
It will be supported when ngx-sweetalert2 supports it. And properly implemented so you don't have to call update() directly but just change the value of `<swal>` inputs.
Also, if you want dynamic content in the dialogs, you may also want to use `*swalPartial` (see the README).

**Comment by limonte** [comment]
Good news!

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```
