### ISSUE TITLE
toast and allowOutsideClick

### ISSUE THREAD

**Issue by ruizenrmar** [sweetalert2/ngx-sweetalert2#115]
Hi!

I create a  message question with toast=true and allowOutsideClick= false, however I can make click outside of toast. If I change toast= false, its works.

https://stackblitz.com/edit/angular-d7fbhj

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/54867864-0b318400-4d8e-11e9-90b0-2a677deaf983.png)
