### ISSUE TITLE
Deprecate @toverux/ngx-sweetalert2

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#117]
Since the package has been renamed, it makes sense to indicate that to users and deprecate the old name the same was as https://www.npmjs.com/package/@toverux/ngsweetalert2 was deprecated.

Since nobody else can do that because of npm permissions, I'm assigning @toverux to this issue.

**Comment by toverux** [comment]
It's done! 
![image](https://user-images.githubusercontent.com/1343250/54877516-17662180-4e20-11e9-999b-0eb2c5417ea7.png)

**Comment by limonte** [comment]
Thank you @toverux!

**Comment by Narshe1412** [comment]
@toverux @limonte Any issues for users moving from
```    "@toverux/ngx-sweetalert2": {
      "version": "4.0.0",```
to the new name?

**Comment by limonte** [comment]
@Narshe1412 there should not be any https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0
