### ISSUE TITLE
SweetAlert queue

### ISSUE THREAD

**Issue by luksfk** [sweetalert2/ngx-sweetalert2#127]
Hi, I would like to know if is there a way to use 'queue' like in the native sweetalert. I saw the 'queue' accessing the nativeSwal, but I also need to use the template from angular by the '*swalPartial'.

**Comment by toverux** [comment]
It is not planned, and I think I won't add support for queues, because that would introduce a significant amount of code and complexity in the library, for a relatively rare use case.
Maybe later, if we can separate features into submodules.
