### ISSUE TITLE
showConfirmButton="false" not working when confirmButtonClass is used Angular 8

### ISSUE THREAD

**Issue by YulianD** [sweetalert2/ngx-sweetalert2#129]
**Hello cordial grettings, after everything, want to say that sweetalert is amazing.**

- **The problem is:**

![1](https://user-images.githubusercontent.com/11492518/63562946-ff0c4700-c524-11e9-9d11-a68b5236223a.PNG)

the confirmation button is always displayed, despite using the option `showConfirmButton: false`

![2](https://user-images.githubusercontent.com/11492518/63562957-07fd1880-c525-11e9-87ff-c887a04eebf3.PNG)

- **Solution:**

Remove `confirmButtonClass`, but this forces me to give him the class every time i want to use the confirmation button

**Comment by limonte** [comment]
FYI `confirmButtonClass` is deprecated and, if you're using the latest version of `sweetalert2`, you should be getting warnings in console.

Please use `customClass` instead and let us know if the issue still there: https://sweetalert2.github.io/#custom-class

**Comment by YulianD** [comment]
> Hello @YulianD and thank you for kind words about SweetAlert2!
> 
> `confirmButtonClass` is deprecated and, if you're using the latest version of `sweetalert2`, you should be getting warnings in console.
> 
> Please use `customClass` instead and let us know if the issue still there: https://sweetalert2.github.io/#custom-class

Tt is right, thanks.

`    SweetAlert2Module.forRoot({`
`      buttonsStyling: false,`
`      showConfirmButton: false,`
`      customClass: {`
`        confirmButton: 'btn btn-success'`
`        cancelButton: 'btn btn-warning'`
`      },`
`    })`
