### ISSUE TITLE
Content views do not get destroyed

### ISSUE THREAD

**Issue by akakira** [sweetalert2/ngx-sweetalert2#130]
So I'm using a form inside the swalTargets.content swalpartial directive. I was checking the validity of the form which is inside a component rendered inside the content in order to enable or disable the done button in a swalTargets.action. I was noticing that the second time i opened the form after submitting the done button never became active. I added a ViewChildren selector and noticed that for each time I submitted the form and closed the window the count of the number of content views went up. The content in the content view is neither destroyed nor reused. Was this behavior intentional? With a modal that gets reused many times, this could be a major memory issue. Thanks!

**Comment by toverux** [comment]
Thank you for your report. Can you send the code that tests this behaviour, and possibly the rest where you use this alert?
I can say that we're destroying the component that hosts your content, and we're detaching it from the change detector. But maybe that's not always sufficient.
I am in the process of rewriting the library (see the [next](https://github.com/sweetalert2/ngx-sweetalert2/tree/next) branch) so I'll be able to verify this and fix it.

**Comment by toverux** [comment]
I tried in the new branch (but the disposal code is virtually identical), and the resources are always liberated and garbage-collected. The components inside *swalPartials also get destroyed. I was not able to make the memory grow as I closed and reopened the modal a great number of times.

Therefore, I'll close this issue, but if you know for sure that something is wrong, please reopen the issue and post a code sample of your experiment so I can understand what you tried to do.
