### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by coilnovasince1985** [sweetalert2/ngx-sweetalert2#134]
I cant properly compile my angular app using

`node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --aot --build-optimizer --prod`

keep receiving the following error:

```
ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at skipSynthesizedParentheses (/Users/app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:73209:44)
```

I've seen this kind of issue previously and it has been closed without a solution

**Comment by toverux** [comment]
Hello,
What version of TypeScript are you using?

**Comment by toverux** [comment]
Hello,
What version of Angular and TypeScript do you use? On what OS?

**Comment by coilnovasince1985** [comment]
@toverux angular 6, "typescript": "^2.7.2"

**Comment by toverux** [comment]
TypeScript 2 is known to have this issue.
Unfortunately we can't do anything other than recommending you to upgrade it.
If you can't upgrade TypeScript but your setup supports SCSS, you can try this solution **1** from here : https://github.com/sweetalert2/sweetalert2/issues/1101#issuecomment-417057957
