### ISSUE TITLE
Property 'show' does not exist on type 'SwalComponent'.

### ISSUE THREAD

**Issue by bnadem** [sweetalert2/ngx-sweetalert2#136]
after installation with command "npm install --save sweetalert2 @sweetalert2/ngx-sweetalert2"

package.json ==>     "@sweetalert2/ngx-sweetalert2": "^6.0.1",
with component in html file 
<swal
  #deleteSwal
  title="Delete {{ file.name }}?"
  text="This cannot be undone"
  type="question"
  [showCancelButton]="true"
  [focusCancel]="true"
  (confirm)="deleteFile(file)">
</swal>

in typescript file :
import Swal, {SweetAlertOptions} from "sweetalert2"
import {SwalComponent} from "@sweetalert2/ngx-sweetalert2"
.
.
.
 **@ViewChild('deleteSwal') private deleteSwal: SwalComponent;**

in function i call     this.deleteSwal.show();

after run i becomme  this error message "**Property 'show' does not exist on type 'SwalComponent**'."

her is my detail my angular version package

ngular CLI: 6.1.1
Node: 10.16.3
OS: linux x64
Angular: 6.1.10
... animations, common, core, forms, http, language-service
... platform-browser, router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.12.4
@angular-devkit/build-angular       0.12.4
@angular-devkit/build-optimizer     0.12.4
@angular-devkit/build-webpack       0.12.4
@angular-devkit/core                7.2.4
@angular-devkit/schematics          0.7.1 (cli-only)
@angular/compiler                   8.2.10
@angular/compiler-cli               8.2.10
@angular/platform-browser-dynamic   8.2.10
@ngtools/webpack                    7.2.4
@schematics/angular                 0.7.1 (cli-only)
@schematics/update                  0.7.1 (cli-only)
rxjs                                6.5.3
typescript                          3.5.3
webpack                             4.28.4

**Comment by toverux** [comment]
`show()` has been renamed to `fire()` in v6 to match SweetAlert2's new terminology.
