### ISSUE TITLE
content dont update dynamic after  detected Change Called?

### ISSUE THREAD

**Issue by bnadem** [sweetalert2/ngx-sweetalert2#138]
Content title, type... dont update dynamic, after run detected Changes
import {..DoCheck..., ApplicationRef... } ..
export Classe test implements OnInit, DoCheck {
    constructor(.....  private ref:ApplicationRef, ..... {

   }
   function (){
/* change proprecty of option */
            this.sw.swalOptions.title="titleToChange";
             this.sw.swalOptions.text= "textToChange";
            this.ref.tick(); //Detect change called her
            this.sw.fire();
  }
 ngDoCheck() {
//function called form Detected Changed after Tick function From ApplicationRef
    console.log('Angular change detection cycle is running.');
  }
in template
<swal #sw [swalOptions]="opt"
>
</swal>

**Comment by toverux** [comment]
Angular do not deep-check the contents of objects. You'll have to either update `[title]` or `[text]` directly, or replace the `this.opt` object (that is bind to `[swalOptions]` in your snippet), like this:

```ts
this.opt = { ...this.swalOptions, title: 'titleToChange', text: 'textToChange' }
```
