### ISSUE TITLE
 Property 'type' does not exist on type 'SweetAlertOptions'.

### ISSUE THREAD

**Issue by sahan93knightz** [sweetalert2/ngx-sweetalert2#140]
I'm using ` "@sweetalert2/ngx-sweetalert2": "^6.0.1"` and `"sweetalert2": "^9.1.5"` with angular 8.
The application fails to compile with the following errors.
```
ERROR in node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(33,29): error TS2339: Property 'type' does not exist on type 'SweetAlertOptions'.
node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(45,45): error TS2339: Property 'customContainerClass' does not exist on type 'SweetAlertOptions'.
node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(61,43): error TS2339: Property 'confirmButtonClass' does not exist on type 'SweetAlertOptions'.
node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(63,42): error TS2339: Property 'cancelButtonClass' does not exist on type 'SweetAlertOptions'.
node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(80,35): error TS2339: Property 'imageClass' does not exist on type 'SweetAlertOptions'.
node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts(89,35): error TS2339: Property 'inputClass' does not exist on type 'SweetAlertOptions'.
```

## Steps to re-produce

1. Create a new Angular App `ng new`
2. Add Sweetalert using `npm install --save sweetalert2 @sweetalert2/ngx-sweetalert2`
3. Import the module into the app. `imports: [SweetAlert2Module.forRoot()],`
4. Run the app `ng serve`

https://imgur.com/gallery/eGK9Eis

**Comment by sahan93knightz** [comment]
Following commits caused the issue
https://github.com/sweetalert2/sweetalert2/commit/c04782c1ae00ffc8150afb23b9510c400b78f0b5#diff-d87248d6b8c6eb63d04cd126e5027842
https://github.com/sweetalert2/sweetalert2/commit/5276cfd1f6a40ce5c510e94dc8840bac6a54e4de#diff-d87248d6b8c6eb63d04cd126e5027842
https://github.com/sweetalert2/sweetalert2/commit/2594115bf7e0940eaf9f3d74f195dbff9d5c2fce#diff-d87248d6b8c6eb63d04cd126e5027842
https://github.com/sweetalert2/sweetalert2/commit/ee7e392998c62e04d7256be9a240c6d509373a0e#diff-d87248d6b8c6eb63d04cd126e5027842

**Comment by umens** [comment]
hey ! @limonte made and merge a fix for that in master but you need to wait for @toverux to publish a new release with the fix. Until then, you can use the sweetalert2 version up to 8.19.0

**Comment by limonte** [comment]
Sorry about this inconvenience!

I published the new major release, please read the release notes with breaking changes: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v7.0.0
