### ISSUE TITLE
Fire swal via template

### ISSUE THREAD

**Issue by ChristofFritz** [sweetalert2/ngx-sweetalert2#145]
Hi all together,

I'd like to fire swal alerts via template without going the ViewChild-way.

Example: 
`<swal *ngIf="(error$ | async) as error" [title]="error.title" [text]="error.text" icon="error"> </swal>`

The really big advantage I see here is, that my redux store does all the work and I don't need to do the show and hide logic.

I'd be really grateful if anybody knows a solution to this. Even a workaround (without 'codebehind') would be fine.

**Comment by ChristofFritz** [comment]
A solution would be that the swal directive always shows the swal if in the dom. Then you would be able to manually show or hide it via the ng-if. This would also adhere better to "the angular way".

**Comment by toverux** [comment]
Interesting use case.
What do you think about a new `[swalFireOnInit]=""true` opt-in option that would do what you describe here?

**Comment by ChristofFritz** [comment]
That would be great! (And maybe default SwalOptions as a partial in the forRoot() would be 🔥 because I'm always setting heightAuto on false)

**Comment by toverux** [comment]
This option will also be available in forRoot().
And to set native SweetAlert options, you can actually already do that in forRoot() too, by providing a SweetAlert mixin, it's just a bit verbose :)

```ts
import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';

// using a separate function for AoT, that doesn't likes arrow syntax expressions in @NgModule
export function provideSwal() {
    return import('sweetalert2').then(({ default: Swal }) => Swal.mixin({
        heightAuto: fgalse
    }))
} 

@NgModule({
    imports: [
        SweetAlert2Module.forRoot({ provideSwal }) // also possible in forChild, btw
    ]
})
export class AppModule {
}
```

**Comment by ChristofFritz** [comment]
You guys are bloody awesome! Right at the perfect moment so I can use it at work womorrow!

**Comment by toverux** [comment]
Yes indeed, the CI is configured with his credentials - got no idea on how to change that, but that's not too bad.

And cool, sorry to have kept you waiting a few days for this though!

**Comment by ChristofFritz** [comment]
No problem at all! After all, it's "just" open source and you are doing it in your free time (i guess?).

**Comment by toverux** [comment]
Yup. Unfortunately not everybody is as comprehensive as you ;)
Do not hesitate in the future if you have other ideas like this! I'll probably use that new feature myself, actually.

**Comment by ChristofFritz** [comment]
It works! (of course it does)
It reduces the code overhead by a lot!

`<swal
    *ngIf="error$ | async as error"
    [text]="error.text"
    [title]="error.title"
    [swalFireOnInit]="true"
    icon="error"
    [swalOptions]="{ customClass: { popup: 'animated fadeIn' } }"
    (confirm)="resolveErrorAction()"
>
</swal>`

**Comment by toverux** [comment]
Hi @ChristofFritz, I've heard you like declarative and reactive code - me too :)
Please know that I've added `[swalVisible]` in 7.2.0, you may like it too: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v7.2.0
Depending on the use case, it may be more or less practical than `[swalFireOnInit]` combined with `*ngIf`. In all cases, this is a new (and more explicit) way to avoid using `fire()` or `dismiss()`.
