### ISSUE TITLE
this.confirm.emit is not a function

### ISSUE THREAD

**Issue by Sireini** [sweetalert2/ngx-sweetalert2#146]
I am trying to redirect the user after confirming the sweetalert. This is my html markup:

`<swal #mmPlusSwal title="Succesvol verstuurd!"	text="Je aanvraag is verzonden, we nemen zo snel mogelijk contact me je op. Je kunt " type="success"	timer="10000" [swalOptions]="{ confirm: swalConfirm, confirmButtonColor: '#ffa000' }"></swal>
`

and this is the method in my typescript file

`public swalConfirm(): void {
	console.log("BUTTON CONFIRM");
}`

But the console throws me this error: 
`ERROR Error: Uncaught (in promise): TypeError: this.confirm.emit is not a function
TypeError: this.confirm.emit is not a function at SwalComponent.<anonymous> (sweetalert2-ngx-sweetalert2.js:392)`

**Comment by toverux** [comment]
Indeed, this replaces the EventEmitter (`@Output() confirm`) from the library. Besides, there is no "confirm" option in SweetAlert2 anyway.
Please use `(confirm)="swalConfirm"` instead :)
