### ISSUE TITLE
Can't set global Swal options

### ISSUE THREAD

**Issue by ux-powered** [sweetalert2/ngx-sweetalert2#150]
Hi,

How to set default Swal options with `forRoot` directive? I tried to do it with `provideSwal`, but this doesn't seem to work for me :/ I'm using Angular 9 and the latest ngx-sweetalert2 release (7.4.0).

`app.module.ts`
```ts
...
import Swal from 'sweetalert2';
import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';

@NgModule({
  ...
  imports: [
    ...
    SweetAlert2Module.forRoot({
      async provideSwal() {
        return Swal.mixin({
          buttonsStyling: false,
          customClass: {
            confirmButton: 'btn btn-lg btn-primary',
            cancelButton: 'btn btn-lg btn-secondary'
          }
        });
      }
    }),
  ]
})
export class AppModule {}
```

`child.module.ts`
```ts
...
import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';

@NgModule({
  imports: [
    ...
    SweetAlert2Module
  ],
...
})
export class ChildModule { }
```

`child.component.html`
```html
<button [swal]="['Success!', 'Success message!', 'success']" class="btn btn-success">
  Success
</button>
```

![image](https://user-images.githubusercontent.com/39078782/74632319-cd5dfb00-51aa-11ea-9d21-3b668e0fb88c.png)
![image](https://user-images.githubusercontent.com/39078782/74632340-dcdd4400-51aa-11ea-9018-233c30dc2af3.png)

**Comment by toverux** [comment]
It looks fine. Can you tell me if your provideSwal() is called?

**Comment by toverux** [comment]
Hi @ux-powered, I tried to replicate but without success: it works fine (dev and prod build) with the latest version of ngx-sweetalert2 and Angular. I also created a submodule.

If you can, please create a project that replicates the problem.

**Comment by ux-powered** [comment]
Thank you for your help, it was my mistake - probably, as described in the "Importing SweetAlert2Module" section of the 6.0.0 migration guide, AoT was removing `provideSwal()` function inside the `@NgModule`. I just extracted the `provideSwal()` to another file and now everything works fine.

swal-options.ts
```ts
import Swal from 'sweetalert2';

export async function provideSwal() {
  return Swal.mixin({
    buttonsStyling: false,
    customClass: {
      confirmButton: 'btn btn-lg btn-primary',
      cancelButton: 'btn btn-lg btn-default'
    }
  });
}
```

app.module.ts
```ts
import { provideSwal } from './swal-options';
import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';

@NgModule({
  ...
  imports: [
    ...
    SweetAlert2Module.forRoot({ provideSwal })
  ]
});
export class AppModule {}
```
