### ISSUE TITLE
Ambient context error

### ISSUE THREAD

**Issue by AndyBraham** [sweetalert2/ngx-sweetalert2#151]
When trying to use the library I get the following error

Error: ERROR in node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:101:9 - error TS1086: An accessor cannot be declared in an ambient context.

**Comment by toverux** [comment]
You are probably using ngx-sweetalert2 ^7.4.0 on Angular 8. Unfortunately, this version is broken on Angular 8. Please install version ~7.3.0 on Angular 8 instead, and ^8.0.0 if you upgrade to Angular 9.

**Comment by AndyBraham** [comment]
Thanks toverux... I was indeed using Angular 8, simply upgraded to 9 and everything works great!
