### ISSUE TITLE
Global options "onOpen" not working

### ISSUE THREAD

**Issue by Art2058** [sweetalert2/ngx-sweetalert2#159]
"@angular/core": "8.2.14"
"sweetalert2": "^9.10.6"
"@sweetalert2/ngx-sweetalert2": "^7.3.0"

* app.module.ts
```
export async function provideSwal() {
  return Swal.mixin({
    buttonsStyling: false,
    customClass: {
      confirmButton: 'btn btn-dark btn-side-margin',
      cancelButton: 'btn btn-light btn-side-margin'
    },
    scrollbarPadding: false,
    showCancelButton: true,
    showCloseButton: true,
    reverseButtons: true,
    padding: '2.5em 1.25em 1.25em',
    showLoaderOnConfirm: true,
    onOpen: () => {
      console.log('opend')
    }
  })
}

@NgModule({
  ...,
  imports: [
    ...,
    SweetAlert2Module.forRoot({ provideSwal })
  ]
})
export class AppModule {}
```

only "onOpen(, onClose, onBeforeOpen, ...)" doesn't work.
why?

**Comment by toverux** [comment]
It is because onOpen is overriden in the `<swal>` component to call the `(open)` event emitter.
It would be possible to restore that feature while conserving the current behavior though. I'll provide a fix soon!
Thanks for the report.

**Comment by Art2058** [comment]
@toverux  Thanks for the comments!!👍
