### ISSUE TITLE
ngx-sweetalert2 popup frozen after doesn't pass validation bind to preconfirm input 

### ISSUE THREAD

**Issue by yesimd** [sweetalert2/ngx-sweetalert2#167]
Hi,
I am using ngx-sweetalert2 for my angular project. I am using preConfirm method to prevent sweetalert popup from resolve if inputs validation fails. But after validation fails popup buttons become disabled so can not use them again. .  My code is below. I will be so appreciate if you can take a look and help to solve this problem. Thanks in advance.
html:
<swal #showSwalDialog (confirm)=saveTicket() [preConfirm] = "validator"
 [swalOptions]="options">
<ng-container *swalPortal="swalTargets.content">
  some inputs
</ng-container>
</swal>

ts:
constructor(){
    this.options = {
      title: 'test',
          text: 'text',
          icon: 'warning',
          confirmButtonColor: '#28a745',
          confirmButtonText: 'confirmButtonText',
          showCancelButton: true,
          cancelButtonColor: '#d33',
          cancelButtonText: 'cancelButtonText',
          reverseButtons: true,
  } as SweetAlertOptions
}

  validator():any | Promise<any>  {
      return new Promise((resolve) => {
        if(control()){
          resolve()         
      }else {
        Swal.showValidationMessage("fails");
        }
      }) 
    }

**Comment by toverux** [comment]
Answered by email.
