### ISSUE TITLE
adding custom input to swal component

### ISSUE THREAD

**Issue by yesimd** [sweetalert2/ngx-sweetalert2#168]
Hi,

I am using ngx-sweetalert in my project and I have more than one input which need validation before confirmation. I used preConfirm input but the problem is after clicking to confirm button if validation fails error message is not ressetted even enter valid inputs until hit the confirm button again. So I need to add a customized input like [preConfirm] to swal component to reset error message if validation pass. I How can I add new input to ngx-sweetalert2 library. Thanks for your help.

**Comment by toverux** [comment]
Hi,

You can add multiple inputs using a custom content with `*swalPortal` (see README).
Then in preConfirm, you'll have to read the contents of the inputs manually.

```html
<input [(ngModel)]="myVar">
```

```ts
export class MyComponent() {
    public myVar: string;
}
```

Finally, you can control the validation message visibility and content with :

Swal.showValidationMessage(message) | Show the validation message DOM node.
Swal.resetValidationMessage() | Hide the validation message DOM node.
Swal.getValidationMessage() | Get the validation message DOM node.
