### ISSUE TITLE
How to disable inject styles in head after angular styles link and not before maybe?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sweetalert2/ngx-sweetalert2#171]
I try to do steps in https://github.com/sweetalert2/ngx-sweetalert2/issues/118

but this doesn't work!

what I did:

1. in sharedModule 
```js
// the function must be outside of @NgModule and exported or the AoT compiler complains
export function provideSwal() {
    return import('sweetalert2/dist/sweetalert2.js'); // instead of import('sweetalert2')
}

....
imports: [
     SweetAlert2Module.forRoot({
            provideSwal
     })
],
exports: [
     SweetAlert2Module
]
```

then in all feature modules import `sharedModule`

**Comment by toverux** [comment]
Hi,

You should use SweetAlert2 source directly instead, see https://github.com/sweetalert2/ngx-sweetalert2/issues/118#issuecomment-527596943
