### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by deepakkoirala** [sweetalert2/ngx-sweetalert2#178]
How can we suppress these warnings? I am using sweetalert 10.8.1. It shows up when it initializes.

sweetalert2.all.js:242 SweetAlert2: "onBeforeOpen" is deprecated and will be removed in the next major release. Please use "willOpen" instead
sweetalert2.all.js:242 SweetAlert2: "onOpen" is deprecated and will be removed in the next major release. Please use "didOpen" instead
SweetAlert2: "onRender" is deprecated and will be removed in the next major release. Please use "didRender" instead.
SweetAlert2: "onClose" is deprecated and will be removed in the next major release. Please use "willClose" instead.
SweetAlert2: "onAfterClose" is deprecated and will be removed in the next major release. Please use "didClose" instead.
SweetAlert2: "onDestroy" is deprecated and will be removed in the next major release. Please use "didDestroy" instead.

**Comment by toverux** [comment]
You cannot (easily) suppress these warnings. This integration still uses the old hooks under the hood, and that's why these warnings are used. You can safely ignore these messages for now, and wait for the next release of ngx-sweetalert2, or you can downgrade sweetalert2 (that, I do not recommend).
