### ISSUE TITLE
Padding-Right added to body on swal fire

### ISSUE THREAD

**Issue by AntonGrekov** [sweetalert2/ngx-sweetalert2#179]
When firing regular(simple swal window) an inline-style: **style="padding-right: 16px"** is added to body tag.
I found related issues in sweetalert home repository. As it's said this issue is fixed in later releases of sweetalert

https://github.com/sweetalert2/sweetalert2/issues/678
https://github.com/sweetalert2/sweetalert2/issues/1168

I guess that padding is needed to compensate vertical scroll bar, is there a way to disable that behaviour via swal options ?

**Comment by limonte** [comment]
1. https://sweetalert2.github.io/
2. Ctrl + F
3. scrollbar

**Comment by AntonGrekov** [comment]
Ty !!!!
