### ISSUE TITLE
Dark theme and styling not working

### ISSUE THREAD

**Issue by umersheikh105** [sweetalert2/ngx-sweetalert2#182]
![bug sweetalert](https://user-images.githubusercontent.com/56246944/108802697-f60b9400-7566-11eb-820f-4bfee073e57b.PNG)

When trying to use the dark theme, I am left this very buggy alert and I am not sure why. I installed and imported just as this page said https://www.npmjs.com/package/@sweetalert2/theme-dark

Also, since the theme did not work, I tried editing the variable.scss file to make it look like the dark theme. Even then it would not change anything. So instead, I did this 
![sweetalert2](https://user-images.githubusercontent.com/56246944/108802876-3834d580-7567-11eb-97b2-661fee6eb830.PNG)

but even that was limited because I could not change the title color nor the input text color

**Comment by limonte** [comment]
This issue report is a mess, sorry. It's reported in the Angular repo, contains React code and it's about the dark theme.
