### ISSUE TITLE
Property 'animation' does not exist on type 'SweetAlertOptions<any, any>'

### ISSUE THREAD

**Issue by jongbonga** [sweetalert2/ngx-sweetalert2#189]
Error: node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:53:34 - error TS2339: Property 'animation' does not exist on type 'SweetAlertOptions<any, any>'.
[ng] 53     animation: SweetAlertOptions['animation'];

**Comment by chidongyh2** [comment]
I've got same issue :(

**Comment by limonte** [comment]
Hey guys! New major versions of `sweetalert2` and `ngx-sweetalert2` have been released. Please use versions according to this table 

![image](https://user-images.githubusercontent.com/6059356/118356310-4817f080-b57d-11eb-8e72-74a0bc89e322.png)

The `animation` param was removed.

And of course do not forget to read the release notes of every major upgrade, there are always breaking changes in major releases:

- `sweetalert2@11`: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0
- `ngx-sweetalert2@10`: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v10.0.0
