### ISSUE TITLE
Swal.clickConfirm() with declarative style.

### ISSUE THREAD

**Issue by hizmarck** [sweetalert2/ngx-sweetalert2#193]
I know that this would be a post on StackOverflow, but I've been searching a lot and I thought that this is most suited for this library, so I'm wondering what is the canonical way to use Swal.clickConfirm(), I didn't find how to implement this with ngx-sweetalert2.

Regards.

**Comment by logan-jobzmall** [comment]
@hizmarck - What I did was take the template reference (e.g. `#swalComponent`) and use:

`
swalComponent.close({
                        isConfirmed: true,
                        isDenied: false,
                        isDismissed: false
              })
`

**Comment by hizmarck** [comment]
> @hizmarck - What I did was take the template reference (e.g. `#swalComponent`) and use:
> 
> `swalComponent.close({ isConfirmed: true, isDenied: false, isDismissed: false })`

I forget to mention that I want to use **clickConfirm() ** conjunction with **preconfirm** to show the loading animation.

I will try to test your suggestion logan, then I comment on how it was.
