### ISSUE TITLE
cant override css in angular

### ISSUE THREAD

**Issue by TheCoderateKid** [sweetalert2/ngx-sweetalert2#197]
Hi I am trying to use this library but the input font-size for the textarea and text boxes are very small and I cant seem to figure out how to over ride the 14px it is default at. I am using angular and showing the popup by code not. I tried setting the font-size in inputAttributes but that did not work either. Thanks in advance for the help!

Swal.fire({
      input: 'textarea',
      title: 'Leave a note',
      confirmButtonColor: '#24b57f',
      width:  '500px',
      inputValue: this.note,
      inputPlaceholder: 'Type your message here...',
      inputAttributes: {
        'aria-label': 'Type your message here',
        'font-size': '24px'
      },
      showCancelButton: true
    })

![sweetalert](https://user-images.githubusercontent.com/73808686/135727206-2444e0f8-6fe5-44d9-ad7c-1e302503d19a.png)

**Comment by TheCoderateKid** [comment]
i basically cannot connect the css to the SWAL objects that are call in the ts file

**Comment by limonte** [comment]
`font-size` is not an attribute, but a CSS property. Use [`customClass`](https://sweetalert2.github.io/#customClass) for adding styles to inputs.
