### ISSUE TITLE
Stricts templates & Angular Language Service

### ISSUE THREAD

**Issue by Pingolus** [sweetalert2/ngx-sweetalert2#206]
Hi,
Thank's for this great lib ! 

Do you know if there's a way to have completion & no errors inside templates with vscode, with Angular Language Service extension ? 

I don't know why, event with the basic example taken from your lib, swal component is not find by the extension (build and runtime both are OK).

Angular Language Service Extension is official and very, very useful to have strict templates checking & autocomplete.

The error message is as simple as that : 'swal' is not a known element

**Comment by limonte** [comment]
not sure what this issue is about, sorry.
