### ISSUE TITLE
Cannot find module @sweetalert2/ngx-sweetalert2 or its corresponding type declarations

### ISSUE THREAD

**Issue by accarvajal** [sweetalert2/ngx-sweetalert2#238]
After installing library and types according documentation, I'm trying to import the module into any module and VS Code is marking import ... from with that error. Package.json shows this in dependencies:

"@sweetalert2/ngx-sweetalert2": "^12.1.0",
"rxjs": "~7.5.0",
"sweetalert2": "^11.7.5",

Recently I upgrade my angular project to v16, despite of many dependencies show a warning when installing, they are working fine. I'm using yarn for package managing.

![image](https://github.com/sweetalert2/ngx-sweetalert2/assets/20478780/1767826b-d309-4158-812b-84213e8a1446)

I tried to fix it by removing node_modules and reinstalling but not success.

**Comment by limonte** [comment]
not sure what this issue is about, sorry.
