### ISSUE TITLE
Angular 5 Support Warning

### ISSUE THREAD

**Issue by mkharibalaji** [sweetalert2/ngx-sweetalert2#43]
Hi @toverux 
      Angular 5.0.3 during installation ,I am able to find the below warnings,

npm WARN @toverux/ngx-sweetalert2@3.0.1 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN @toverux/ngx-sweetalert2@3.0.1 requires a peer of @angular/common@^4.0.0 but none was installed.

**Comment by toverux** [comment]
Hi @mkharibalaji, 

Yes, ngx-sweetalert2 uses a packaging tool that's not officially supprting Angular 5 yet, however no problems are observed with ngx-sweetalert2 for now (and ng-packagr seems almost ready), so I'll soon release a new version with adjusted peer dependencies. So you should have no more problem than a warning.
I'm just a bit busy those last times so I didn't have the time to give the library enough love (hence the delay in my answer), but stay tuned.

**Comment by toverux** [comment]
Angular 5 is now allowed in the peer dependencies and is officially supported starting with version [v3.1.0](https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v3.1.0).
