### ISSUE TITLE
100 ★

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#46]
Congratulations with the first remarkable milestone :tada: :tada: :tada: 

![](https://media0.giphy.com/media/NXvbWznxGifYc/giphy.gif)

Many thanks @toverux for making the Angular community a bit better. Hopefully, in the near future, we will be able to provide integrations for Vue and React as good as this one.

Have a nice Sunday!

**Comment by toverux** [comment]
Thanks a lot! :smile:

It's the first time for me! When I first published my wrapper (tired of copy-pasting it from project to project), I wouldn't have expected it to have "so much" success, especially when I saw that there were already a lot of packages (but only service wrappers).

I'll be there for the next 100 o/
