### ISSUE TITLE
Opening Sweetalert from Typescript

### ISSUE THREAD

**Issue by andygroat** [sweetalert2/ngx-sweetalert2#50]
Hi, all your examples show how to display an alert from the view in html, I was wondering how you would display it from the typescript.  For example, displaying a success alert once data has been posted to the server.

**Comment by toverux** [comment]
It's implicitly explained in the readme ;)

> You can access the dialog from your TypeScript code-behind like this:
```typescript
class MyComponent {
  @ViewChild('deleteSwal') private deleteSwal: SwalComponent;
}
```

Then, just call `this.deleteSwal.show()` where you want to display the modal. You can `await` it too.
