### ISSUE TITLE
How to .showLoading() or any other method from native sweetalert2?

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#51]
Hello @toverux!

Today I posted the announcement post about SweetAlert2 in r/javascript and it instantly became the today's hottest, I expect getting into GitHub trending/js in a couple of hours :)  
 
There's a question about Angular integration: https://www.reddit.com/r/javascript/comments/7x0dpk/sweetalert2_a_beautiful_responsive_highly/du4v6vk/

If you could answer there, it would be great.

Thanks in advance!

**Comment by toverux** [comment]
> Today I posted the announcement post about SweetAlert2 in r/javascript and it instantly became the today's hottest
Wow, awesome!

> If you could answer there, it would be great.
Done!

**Comment by limonte** [comment]
I guess ngx-sweetalert2 will get new happy users as well: 

![](https://i.imgur.com/2QcjSfA.png)
