### ISSUE TITLE
404 importing  SweetAlert2Module

### ISSUE THREAD

**Issue by michelmob** [sweetalert2/ngx-sweetalert2#55]
Hi @toverux,

I'm trying to integrate ngx-sweetalert2 with my angular 5 app but I'm receiving a 404 whe  importing the:

`import { SweetAlert2Module } from '@toverux/ngx-sweetalert2';`

**Comment by toverux** [comment]
Hello @michelmob,

This is related to your build setup.
What bundling tools are you using? Angular CLI? What URL is 404-ing?

**Comment by michelmob** [comment]
Hi @toverux, I'm using angular cli 1.67 but, this application is using VIsualStudio 2017 and angular cli  1.6.7.

**Comment by michelmob** [comment]
HI @toverux , you are correct, I have to configure correctly, thank you so much. I'll post the configuration here later. 
Thanks!

**Comment by toverux** [comment]
Yes, I'd be interested to know what was the problem, I don't use Angular CLI often. It can help other people, and if it's a general issue of ngx-sweetalert2 + Angular CLI, I can document it in the documentation.

**Comment by toverux** [comment]
I'm closing this, don't forget to post your problem and solution if you still can :)

**Comment by VSKerberos** [comment]
> HI @toverux , you are correct, I have to configure correctly, thank you so much. I'll post the configuration here later.
> Thanks!

Hi, I am dealing with same problem how did you solve the problem ? Thanks
