### ISSUE TITLE
Issue in angular 4

### ISSUE THREAD

**Issue by krupatj** [sweetalert2/ngx-sweetalert2#56]
I am getting this error.
sweetalert2.d.ts (231,18): In ambient enum declarations member initializer must be constant expression

**Comment by toverux** [comment]
Hello @krupatj,

Indeed, this is an issue in SweetAlert2's declaration file (this is not specific to this repo). I'm a contributor on it so I'll fix that asap.

In the meantime you can workaround this error by upgrading your version of TypeScript to 2.4 (if that does not breaks other things for you). String enums have been added in 2.4, and SweetAlert2's .d.ts uses this feature.

**Comment by toverux** [comment]
The fix has been released, please upgrade **`sweetalert2`** to version `^7.12.15` :)
