### ISSUE TITLE
Modifying component options on the go.

### ISSUE THREAD

**Issue by pupizoid** [sweetalert2/ngx-sweetalert2#58]
Hi! i'm trying to make something like a dialog for user with ngx-sweetalert2.

For this purpose I put tag in my component template. The dialog implements the following behavior:

1. User enters some data into the dialog form and press confirm.
2. Angular processes given data and in some cases generates an error.
3. An error displayed to user.

I'm trying to reuse existing swal for displaying an error, and it works but not completly, here is the code I use in my component:
```typescript
export class SampleComponent {
  @ViewChild('swal') swal: SwalComponent;

  someAction() {
    try {
      // here data processing
    } catch (e) {
      this.swal.type = 'error';
      this.swal.title = 'Error!';
      this.swal.text = 'Some error message';
      this.swal.show();
    }
  }
}
```
The problem is that swal type & title changes correctly and shown to the user, but not the swal.text...

Maybe there is no such possibility to reuse existing swal component, please clarify this for me. Thanks!

**Comment by cmglez10** [comment]
Same problem here.

I'd tried defining those attributes as dynamic:

```
<swal
  #defaultSwal
  [showCancelButton]="false"
  [text]="swalconfig.default.text"
  [type]="swalconfig.default.type"
</swal>
```

... defined in my component as:

```
swalconfig = {
    default: {
      type:"success",
      text:""
    }
  }
```

And changing them just before show the sweetalert:

```
 this.swalconfig.default.text = this.utilsService.translate(message);
    this.swalconfig.default.type = type;
    this.defaultSwal.show();
```

Result: No type icon and no text. An empty sweetalert with only the confirm button.

![sweetalertissue](https://user-images.githubusercontent.com/6949675/37517008-6b00a346-2910-11e8-8923-66c0849a00d6.png)

**Comment by Nenillo** [comment]
What I did to make it work is the following. Use the text attribute:

`<swal ... [text]="errorText"></swal>`

Use setTimeout in component controller:

`
this.errorText = 'Error message';
setTimeout(() => { this.swal.show(); });
`

**Comment by toverux** [comment]
You'll have to run a detection change cycle just before showing the alert: https://angular.io/api/core/ApplicationRef#tick

Otherwise, the binding isn't updated before the dialog is shown.

And indeed, the library does not supports dynamic changes (yet) because SweetAlert2 has no consistent API to do that properly. An alternative is to use *swalPartial to use dynamic Angular content in the dialog.

**Comment by KalanaPerera** [comment]
@pupizoid thanks you saved my time
