### ISSUE TITLE
I want to use another Component as templates?

### ISSUE THREAD

**Issue by JimWang1995** [sweetalert2/ngx-sweetalert2#60]
<button [swal]="login">Login</button>
<swal title="Login" #login>
   <app-login></app-login> 
</swal>

**Comment by toverux** [comment]
What are you trying to achieve? Is *swalPartial what you're looking for?

**Comment by toverux** [comment]
No, this is an Angular limitation.
References like this are only possible in the same template.
There is a way to workaround that by retrieving the reference in TypeScript with `@ViewChild`, and then passing ot to the parent component, which would assign that to the button.
But I suggest to find another solution. Find another solution that do not violates responsibilities, decouple your components a little bit more. The child component could have a public method that displays the swal, that the parent could call.
