### ISSUE TITLE
How to persist scroll position when opening the alert?

### ISSUE THREAD

**Issue by blopez2010** [sweetalert2/ngx-sweetalert2#61]
If I have a lot of content below in the page, like a table with a large amount of items and I want to delete the last one or one in the middle, the scroll resets making the user scroll down again when the action is completed or canceled.

How can I persist the scroll position in this case?

**Comment by toverux** [comment]
Looks like a SweetAlert2 issue.
ngx-sweetalert2 does not touches the DOM not it does scroll manipulations.
