### ISSUE TITLE
after following the doc, i am getting this issue

### ISSUE THREAD

**Issue by musman92** [sweetalert2/ngx-sweetalert2#66]
Can't bind to 'swal' since it isn't a known property of 'button'

**Comment by yarrgh** [comment]
If this is in a sub module, make sure you're importing `SweetAlert2Module` into that module.

**Comment by toverux** [comment]
Yes. Your application module has most likely no knowledge of the SweetAlert2 module.

**Comment by suhailkc** [comment]
I have using in the sub module (lazy load module). and I had imported `SweetAlert2Module ` but the same error. What would be the issue???
