### ISSUE TITLE
clicking on confirm button closes the swal 

### ISSUE THREAD

**Issue by mahit777** [sweetalert2/ngx-sweetalert2#68]
hitting the confirm button closes the swal is this an expected behaviour? If so how can I implement the [loading example](https://sweetalert2.github.io/) shown in the examples? my swal code is

`<swal #saveSwal 
   title="Are you sure?"
   text ="Do you want to save changes"
   cancelButtonColor="#d33"
   showCancelButton="true"
   cancelButtonText="No! Review"
   confirmButtonColor="#3085d6"
   confirmButtonText='Yes, Save progress'
   (confirm)="save()"
   [showLoaderOnConfirm]="true"
   
   [focusCancel]="true">
</swal>
`

is there a way to keep the swal open and show the loading animation untill an async operation is compleeted ?

**Comment by Niladri24dutta** [comment]
@mahit777  check this stackoverflow answer which I posted few days back , it might answer your question 
https://stackoverflow.com/questions/49961790/clicking-on-confirm-button-closes-the-swal/50040554#50040554

**Comment by toverux** [comment]
Yes, this is expected, that's how SweetAlert2 works.
Please see the SweetALert2 documentation about preConfirm or @Niladri24dutta's answer on SO.

**Comment by vinayistar** [comment]
Not Working. I tried out
 `this.alertOption = {
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33"
  }`
in constructor but still its overriding red color css.
