### ISSUE TITLE
How Programatically Triggering Simple Success Message On Successfull Http Call ?

### ISSUE THREAD

**Issue by shivarajnaidu** [sweetalert2/ngx-sweetalert2#70]
How Programatically Triggering Simple Success Message On Successfull Http Call ?

Like we do in swal js 

```js
swal({
  position: 'top-end',
  type: 'success',
  title: 'Your work has been saved',
  showConfirmButton: false,
  timer: 1500
})
```

**Comment by toverux** [comment]
Hello @shivarajnaidu, the first readme line partially answers your question :

> This is not a regular API wrapper for SweetAlert (which already works very well alone), it intends to provide Angular-esque utilities on top of it.

Read: nothing prevents you from doing this:

```typescript
import swal from 'sweetalert2';

// somewhere in your component
swal({
  position: 'top-end',
  type: 'success',
  title: 'Your work has been saved',
  showConfirmButton: false,
  timer: 1500
});
```

This library takes a declarative approach, to decouple UI logic and more business-y logic in your TypeScript. You may, or may not use it or prefer it over the classic imperative API.

You can also declare your swal using `<swal>` and then use it from the TypeScript:

```
class MyComponent {
  @ViewChild('mySwal') private mySwal: SwalComponent;

  public async doHttpCall(): Promise<void> {
    await httpCall();
    await this.mySwal.show();
  }
}
```

I personally like to have alerts and dialogs declared like any other UI components. But if you don't care about this, then you can still use SweetAlert2 like everyone else. Angular won't bite you.

**Comment by chinthu** [comment]
after updating to 8.1.1 the above approach 

import swal from 'sweetalert2';

// somewhere in your component
swal({
  position: 'top-end',
  type: 'success',
  title: 'Your work has been saved',
  showConfirmButton: false,
  timer: 1500
});


shows following error..

Module '"sweetalert2"' has no exported member 'SweetAlertUpdatableParameters'. Did you mean to use 'import SweetAlertUpdatableParameters from "sweetalert2"' instead?
