### ISSUE TITLE
Disable confirm button until a check is done.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [sweetalert2/ngx-sweetalert2#77]
Hello,

I sm using sweetalert for all alerts and for delete I need to ask the user to type in something as a verification step. When doing that I need to enable the confirm button only when the text typed matches the text shown. Currently I am not able to add a property to the confirm button like 'disabled'.

I am also using the targets for defining the content and the buttons as well.
I also tried to use custom buttons inside the content itself to solve the purpose but I am not able to close the alert shown from the template. When I try calling swal.close() from ts method, it closes the alert but still has the popup modal open and we need to click outside to close that small div.

Please let me know if there are any workaround for the same.

Code:
```
<ng-container *swalPartial="swalTargets.confirmButton">
            Delete Client
          </ng-container>
          <ng-container *swalPartial="swalTargets.cancelButton">
            Dont Delete
          </ng-container>
```

**Comment by toverux** [comment]
There is no way to do that easily and reactively (yet).
You can do it imperatively via the native SweetAlert2 function `swal.disableConfirmButton()` though, in your TypeScript file.

I'd do something like that: https://stackblitz.com/edit/github-9rximv?file=demo%2Fapp%2Fapp.component.html

**Comment by VigneshVaidyanathan** [comment]
Thanks that worked for me
