### ISSUE TITLE
Ready event after ngOnChanges in the component.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [sweetalert2/ngx-sweetalert2#78]
Hello,

I am trying to dynamically pass the options to the swal component and on click of buttons it is going to modify the object being passed inturn calling the ngOnChanges method to update the options. I am also triggering the swal.show() method to show the component.

I am not seeing the change in the options in the current swal component shown, but the next time it is triggered. Since I am calling swal.show() right after changing the options object, I think it is firing the show method before the ngOnChanges is done processing.

Is it possible to add a onReady event emitter to subscribe and then show the component there or have a timer for 100ms before showing the swal component or is there a better way for it.

```
this.swalOptions = {
      reverseButtons: true,
      buttonsStyling: false,
      confirmButtonClass: "btn btn-danger btn-medium swal-button",
      cancelButtonClass: "btn btn-default btn-outline btn-medium swal-button"
};
this.deleteSwal.show();
```

Thanks a lot.

**Comment by toverux** [comment]
It is probably the same problem as here https://github.com/sweetalert2/ngx-sweetalert2/issues/58#issuecomment-389662930

But in you case I'd recommend to modify the component options directly (not through a template binding, ie `this.deleteSwal.options = { ... }`), it makes more sense.

In any other case, you have to wait for the next detection change cycle from Anguilar, either via ApplicationRef.tick, setTimeout(fn, 0) and other tricks like that.
