### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by allamgr** [sweetalert2/ngx-sweetalert2#79]
I'm having the following issue

ERROR in Error: Metadata version mismatch for module [proyect_path]/node_modules/@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.d.ts, found version 4, expected 3, resolving symbol AppModule

**Angular CLI**: 1.7.4
**Node**: 8.11.1
**OS**: win32 x64
**Angular**: 4.4.6
**typescript**: 2.3.4
**webpack**: 3.11.0

When I update the module version to 3 on **toverux-ngx-sweetalert2.metadata.json** the error disappear.

But I know that this is not a good solution for that.

Why its not working with angular 4?

**Comment by dynacorp** [comment]
you are using angular 4 or lower... try upgrading to angular 6 @allamgr

**Comment by allamgr** [comment]
But I do no want to update to angular 6, I have to use the version 4.

What can I do in that case @dynacorp ?

**Comment by dynacorp** [comment]
uninstall it then install version 3.0.1 by adding @3.0.1
