### ISSUE TITLE
200 ★

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#82]
Congratulations with the second remarkable milestone :tada: :tada: :tada:

<img src="https://i.giphy.com/media/q9KaEjVuKcpl6/giphy.webp" width="500">

Keep up the good work @toverux and have a pleasant week!

PS. If you don't know who are those ass-shaking weirdos from the gif above, find out who are Rick and Morty, I discovered them recently and that's definitely something rare and remarkable on Netflix.

**Comment by toverux** [comment]
41 more since you posted and now that I'm reading you :o
Thanks a lot!

PS: A lot of friends recommended me Rick & Morty, I'll watch it someday soon!

**Comment by limonte** [comment]
Glad to see you back! I have bad news: Rick and Morty have been removed from Netflix 😭
