### ISSUE TITLE
Grant npm read-write access to sweetalert2 collaborators

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#85]
Currently, there are 5 SweetAlert2 collaborators: 

```sh
npm access ls-collaborators sweetalert2
{
  "toverux": "read-write",
  "samturrell": "read-write",
  "acupajoe": "read-write",
  "zen_flow": "read-write",
  "limonte": "read-write"
}
```

That will ensure that if bus-factor will happen to @limonte, `sweetalert2` might still be maintained by the rest of the collaborators.

On the other hand, 

```sh
npm access ls-collaborators @toverux/ngx-sweetalert2
{
  "toverux": "read-write"
}
```

So, if something will happen to @toverux, the project (or at least npm package name) will be :skull_and_crossbones: 

--- 

Is it okay for you @toverux to align the list of collaborators with the one from sweetalert2? As I understand correctly, it could be done by running:

```sh
npm access grant read-write sweetalert2 
```

from the `ngx-sweetalert2` directory.

**Comment by toverux** [comment]
Hi @limonte!

It seems that npm doesn't understand this command, but I don't know why:

```
⚡ npm access grant read-write sweetalert2
npm ERR! team is required and must be of type string
npm ERR! 
npm ERR! Usage:
npm ERR! npm access public [<package>]
npm ERR! npm access restricted [<package>]
npm ERR! npm access grant <read-only|read-write> <scope:team> [<package>]
npm ERR! npm access revoke <scope:team> [<package>]
npm ERR! npm access ls-packages [<user>|<scope>|<scope:team>]
npm ERR! npm access ls-collaborators [<package> [<user>]]
npm ERR! npm access edit [<package>]
```

Got any ideas?

**Comment by toverux** [comment]
Latest : 6.4.1. I'll see if there's an issue for that or create one myself. Ah, the legendary stability of npm...

**Comment by limonte** [comment]
> I'll see if there's an issue for that or create one myself.

You can't :D They moved recently from https://github.com/npm/npm to https://github.com/npm/cli and it's not possible to report an issue there :)

npm is crap, I pray for decentralized registry for JS community to happen in future :)

**Comment by limonte** [comment]
ping

**Comment by toverux** [comment]
Well...

```
⚡ npm access grant read-write toverux:sweetalert2 @toverux/sweetalert2
npm ERR! code E404
npm ERR! 404 Team not found : -/team/toverux/sweetalert2/package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/morgan/.npm/_logs/2018-11-08T22_01_10_114Z-debug.log
```

Please tell me I'm missing something :(

**Comment by limonte** [comment]
Closing as irrelevant after changing the package name in https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0
