### ISSUE TITLE
Support for unit testing frameworks on pages with <swal /> components

### ISSUE THREAD

**Issue by MartinMcLaughlin** [sweetalert2/ngx-sweetalert2#86]
When testing pages using Jest or Jasmine with <swal> components or partials, importing the module or component at the top of the page leads to the following error.

                                                                                                            ```                                                                                                                
    StaticInjectorError[InjectionToken SwalDefaults]:                                                                                                                                                                           
      StaticInjectorError[InjectionToken SwalDefaults]:                                                                                                                                                                         
        NullInjectorError: No provider for InjectionToken SwalDefaults! 
```

The alerts are working all over the app, and regular Swal() in the code work fine, even in tests.

Any help is appreciated!

**Comment by oneEyedSunday** [comment]
Hello @MartinMcLaughlin did you figure this out. I need to test that my confirm method was called on confimation. ANy pointers? I dont wanna have to query the DOM and all that.

**Comment by MartinMcLaughlin** [comment]
> Hello @MartinMcLaughlin did you figure this out. I need to test that my confirm method was called on confimation. ANy pointers? I dont wanna have to query the DOM and all that.

Unfortunately I haven't figured this out.

**Comment by oneEyedSunday** [comment]
Oh, thanks for the response.

**Comment by michaeljota** [comment]
I have some issues with SweetAlert and my unit testing. I'm using [ng-mocks](https://github.com/ike18t/ng-mocks) for mocking the components and directives. 

I just created another NgModule with mocked versions of the components and directives exported by the real SweetAlert2Module. Replacing the SweetAlert2Module with my mocked version allow me to use swal components mocked with no behavior.

**Comment by toverux** [comment]
`No provider for InjectionToken SwalDefaults` means that you (probably?) didn't use forRoot and therefore, you haven't provided that token to the library, which needs it.
If you need more help please open a new issue, showing how you declared your tests.

**Comment by prmkishor** [comment]
Unit testing with sweetAlert is very easy and handy. Please folor this link https://github.com/prmkishor/sweetAletUnitTesting/wiki/sweetAlert2-Angular-Unit-Testing
