### ISSUE TITLE
SWAL renders in a weird way

### ISSUE THREAD

**Issue by Sauravsam85** [sweetalert2/ngx-sweetalert2#91]
I am using the following angular components:
"@angular/animations": "^4.4.4",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "bootstrap": "4.1.3",
The following version of ngx-sweetalert: "@toverux/ngx-sweetalert2": "^4.0.0".
The following version of sweetalert: "sweetalert2": "^7.28.2"

On trying to render sweetalert2 using the following code:
<swal #deleteSwal
      title="Delete ?"
      text="This cannot be undone"
      type="question"
      [showCancelButton]="true"
      [focusCancel]="true"
      (confirm)="edit($event)">
</swal>
The dialog box open as shown:
![image](https://user-images.githubusercontent.com/32314270/46211474-9ced9680-c301-11e8-8bc8-120553286e7a.png)

I am also using swal as shown below (not defined in the HTML, but only in typescript)
swal({
    title: 'Deleted!',
    text: 'Holiday has been deleted.',
    type: 'success',
    confirmButtonClass: "btn btn-success",
    buttonsStyling: false
})

This renders fine.

Any idea what am I missing. Anything that I add in HTML under SWAL tag renders vertically and I cannot click on any buttons or interact with it. Can only use ESC to close it.

@toverux  I will appreciate if you can look into this.
Thanks.

**Comment by Rathdor** [comment]
I had the same problem and it was old sweetalert css still loaded in my code.

Remove all sweetalert.css files from other versions and it will work fine

**Comment by toverux** [comment]
@Rathdor is probably right.
Remember, this library is pure logic. If you encounter a rendering problem like this, it's probably due to your usage of the library or it's an issue of the upstream repo, sweetalert2.
