### ISSUE TITLE
problem On angular 7

### ISSUE THREAD

**Issue by seebosmile** [sweetalert2/ngx-sweetalert2#96]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'swal' since it isn't a known property of 'button'. ("
    </mat-card>
  </div>
  <button [ERROR ->][swal]="['Oops!', 'This is not implemented yet :/', 'warning']">
    Do it!
  </button>
"): ng:///AuthenticationModule/RegisterComponent.html@135:10
Error: Template parse errors:
Can't bind to 'swal' since it isn't a known property of 'button'. ("
    </mat-card>
  </div>
  <button [ERROR ->][swal]="['Oops!', 'This is not implemented yet :/', 'warning']">
    Do it!
  </button>

**Comment by seebosmile** [comment]
> `SweetAlert2Module` in your module

 SweetAlert2Module Imported in module.

**Comment by sergio-new-developer** [comment]
Hello!
Same problem with version sweetalert2@ > 7.8.0 when trying to migrate to 8.x

**Comment by limonte** [comment]
Good day fellas and sorry for the delay in delivering the news.

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```
