### ISSUE TITLE
Purportedly incompatible with Angular 7

### ISSUE THREAD

**Issue by rmckeel** [sweetalert2/ngx-sweetalert2#99]
I am in process of manually (non-ng cli) upgrading an Angular project.  For Angular 7 `yarn install`, I get this:

`@toverux/ngx-sweetalert2@4.0.0" has incorrect peer dependency "@angular/core@^5.0.0 || ^6.0.0"
@toverux/ngx-sweetalert2@4.0.0" has incorrect peer dependency "@angular/common@^5.0.0 || ^6.0.0"`

It seems this requires a simple package.json tweak and tagged release of 4.0.1 or similar to get it compatible with 7.  Thoughts?  Thanks!

**Comment by limonte** [comment]
Good news!

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```
